// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePost = "Post"

// Post mapped from table <Post>
type Post struct {
	ID        int32     `gorm:"column:id;primaryKey;default:nextval('"Post_id_seq"" json:"id"`
	CreatedAt time.Time `gorm:"column:createdAt;not null;default:CURRENT_TIMESTAMP" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updatedAt;not null" json:"updatedAt"`
	Title     string    `gorm:"column:title;not null" json:"title"`
	Content   string    `gorm:"column:content" json:"content"`
	Published bool      `gorm:"column:published;not null" json:"published"`
	AuthorID  int32     `gorm:"column:authorId;not null" json:"authorId"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
