// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTodo = "Todo"

// Todo mapped from table <Todo>
type Todo struct {
	ID   int32  `gorm:"column:id;primaryKey;default:nextval('"Todo_id_seq"" json:"id"`
	Name string `gorm:"column:name" json:"name"`
}

// TableName Todo's table name
func (*Todo) TableName() string {
	return TableNameTodo
}
